# Site settings
title: FOAM Science; Doing CFD
description: > 
        FOAM Science is a Computational Fluid Dynamics blog aiming to be a place for OpenFOAM users to share
        and gather knowledge about CFD related subjects.
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: 'https://foamscience.github.io' # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'

# Your information
email: elwardifadeli@gmail.com
author: M. Elwardi Fadeli
#avatar: "//www.gravatar.com/avatar/elwardifadeli@gmail.com_md5?d=mm&s=135"
#avatar: "/assets/img/FoamScience/foamscience-logo-400x400-transparent.jpg"
avatar: "/me/assets/images/profile-round.png"
profile: 
#twitter_username: twitter_username
github_username:  FoamScience
profile_links:
  Email: "mailto:elwardifadeli@gmail.com"
  LinkedIn: "https://linkedin.com/in/elwardi-fadeli"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: foamscience   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    Home: /
    About: /about/
    Contact: /contact/
    Category: /category/
    Tags: /tags/

permalink: /:title/
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
